version: "2"
services:
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=America/Bogota
      - SUBDOMAINS=subdomain
      - TOKEN=token
      - LOG_FILE=false #optional
    restart: always
