version: '3'
services:
  postgresql:
    image: postgres:9.6
    env_file:
      - database.env 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data:
    external: false